### ISSUE TITLE
Use the value receiver instead of the pointer receiver in Pubkey.Identity() (Triage on ostracon#492)

### ISSUE THREAD

**Issue by 0Tech** [Finschia/cometbft#10]
The subject of the triage:
- Finschia/ostracon#492

**Comment by Mdaiki0730** [comment]
It seems that crypto/composite/composite.go does not exist at the stage of v0.38.0.
https://github.com/cometbft/cometbft/tree/v0.38.0/crypto

crypto/composite/composite.go was experimentally introduced in ostracon#194 for BLS signatures and removed in ostracon#541.
https://github.com/Finschia/ostracon/pull/194
https://github.com/Finschia/ostracon/pull/541

It seems that there is no need to reflect it in cometbft.
