### ISSUE TITLE
Update the http status code handling on upnp (Triage on ostracon#497)

### ISSUE THREAD

**Issue by 0Tech** [Finschia/cometbft#11]
The subject of the triage:
- Finschia/ostracon#497

**Comment by Mdaiki0730** [comment]
It seems that p2p/upnp/upnp.go does not exist at the stage of v0.38.0.
https://github.com/cometbft/cometbft/tree/v0.38.0/p2p

p2p/upnp/upnp.go was considered for removal in cometbft#1113 and removed in cometbft#1114.
https://github.com/cometbft/cometbft/issues/1113
https://github.com/cometbft/cometbft/pull/1114

It seems that there is no need to reflect it in cometbft.
