### ISSUE TITLE
Fix overriding tx index of duplicated txs (Triage on ostracon#498)

### ISSUE THREAD

**Issue by 0Tech** [Finschia/cometbft#12]
The subject of the triage:
- Finschia/ostracon#498

**Comment by Mdaiki0730** [comment]
It seems that it is not applied as of v0.38.0.
https://github.com/cometbft/cometbft/blob/v0.38.0/state/txindex/indexer_service.go
https://github.com/cometbft/cometbft/blob/v0.38.0/state/txindex/indexer_service_test.go

This has been removed by tendermint#9473 and the logic has been moved to kvindexer.
https://github.com/tendermint/tendermint/pull/9473

It seems that there is no need to reflect it in cometbft.
