### ISSUE TITLE
Metrics for additional consensus step duration(Triage on ostracon#126)

### ISSUE THREAD

**Issue by 0Tech** [Finschia/cometbft#45]

**Comment by jaeseung-bae** [comment]
* Opinion
  * Not to apply
* Reason
  * Hard to apply to upstream, because of compatibility
  > ex) (ostracon) BlockIntervalSeconds metrics.Gauge != (cometbft) BlockIntervalSeconds metrics.Histogram
  * In my opinion, not all metrics are necessary all the time.
  * How about we put custom metrics such as BlockAppCommitTime metrics.Gauge when it needs(such as performance test)
