### ISSUE TITLE
Add more prometheus metric for block exec, commit and tx recheck

### ISSUE THREAD

**Issue by 0Tech** [Finschia/cometbft#46]
The subject of the triage:
- Finschia/ostracon#132

**Comment by tkxkd0159** [comment]
cometbft still doesn't log following metrics
* `BlockExecutionTime` : gauge value for measuring `execBlockOnProxyApp`<BeginBlock, DeliverTx, EndBlock> processing time => cometbft log this as histogram value
* `BlockCommitTime` : gauge value for measuring `blockExec.Commit` processing time
* `RecheckTime` :  gauge value for measuring `mempool.Recheck` processing titme
This is not core feature. So it depends on personal preference. We need to suggest it to upstream if we really need to aggregate this metrics.

**Comment by 0Tech** [comment]
We should consult with the clients about the usage.

**Comment by tkxkd0159** [comment]
Need to follow up at #53
