### ISSUE TITLE
Fix a pref branch's metrix bug (ostracon#133)

### ISSUE THREAD

**Issue by 0Tech** [Finschia/cometbft#47]

**Comment by loloicci** [comment]
https://github.com/Finschia/ostracon/pull/133 makes setting the time how long rechecking mempool takes in metrics (https://github.com/Finschia/ostracon/pull/133/files#diff-f71975385bf5bc21c04eb08f496140cc8cca405b8dbd7b628342e6d8afb61cc5R590) during updating mempool, even if mempool has no tx in it.

There are no info why this fix is needed in ostracon ropository.

**Comment by loloicci** [comment]
This is a fix for https://github.com/Finschia/ostracon/commit/fa2c02ddf4e7debdb330a133ff01a1673fd369ec. If we need https://github.com/Finschia/ostracon/commit/fa2c02ddf4e7debdb330a133ff01a1673fd369ec, this PR is needed, too.

This looks used only for performance checks.

**Comment by loloicci** [comment]
comentbft does not have https://github.com/Finschia/ostracon/commit/fa2c02ddf4e7debdb330a133ff01a1673fd369ec.
So this PR is not needed.

https://github.com/Finschia/ostracon/commit/fa2c02ddf4e7debdb330a133ff01a1673fd369ec adding `RecheckingTime` in mempool's metrics.
