### ISSUE TITLE
Add more prometheus metrics(`BlockAppCommitTime`, `BlockUpdateMempoolTime`)

### ISSUE THREAD

**Issue by 0Tech** [Finschia/cometbft#49]
The subject of the triage:
- Finschia/ostracon#146

**Comment by tkxkd0159** [comment]
Similar to #46

Just add more prometheus metrics(`BlockAppCommitTime`, `BlockUpdateMempoolTime`)

**Comment by 0Tech** [comment]
We should consult with the clients about the usage.

**Comment by tkxkd0159** [comment]
Follow up at #53
