### ISSUE TITLE
Perf: prevent from flushing in WAL(Triage on ostracon#273)

### ISSUE THREAD

**Issue by 0Tech** [Finschia/cometbft#5]

**Comment by jaeseung-bae** [comment]
* Opinion
  * Not to apply
* Reason
  * Upstream has decided not to apply This PR. (https://github.com/tendermint/tendermint/pull/ 6698)
   > Some of the developers from upstream seem to not want any logic in WAL.

**Comment by 0Tech** [comment]
The upstream is planning on removing WAL.
