### ISSUE TITLE
Add some timing info log (ostracon#324)

### ISSUE THREAD

**Issue by 0Tech** [Finschia/cometbft#51]
The subject of the triage:
- Finschia/ostracon#324

**Comment by loloicci** [comment]
https://github.com/Finschia/ostracon/pull/324 adds some time info to info logs. This looks to be able to be merged into cometbft and to be suggested upstream.

**Comment by Mdaiki0730** [comment]
@loloicci 
Do you know the background behind why it became necessary to log this information at info level?

**Comment by loloicci** [comment]
In our team, this info log is not used by other backends/middlewares. So now we can delete this info log.

**Comment by loloicci** [comment]
> Do you know the background behind why it became necessary to log this information at info level?

I didn't know that, but I heard and researched that this is no more needed.
